version: '3.8'

services:
  # Banco de Dados
  db:
    image: postgres:15
    container_name: devloop-db
    environment:
      POSTGRES_DB: devloop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  # Backend (Spring Boot API)
  backend:
    build: .
    container_name: devloop-api
    ports:
      - "8080:8080"
    depends_on:
      - db

  # Frontend (Nginx servindo HTML/CSS/JS)
  frontend:
    image: nginx:alpine
    container_name: devloop-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend